plugin: amazon.aws.aws_ec2
regions:
  - us-east-2
filters:
  instance-state-name: running
keyed_groups:
  - key: tags.role
    prefix: role
compose:
  ansible_host: public_ip_address
hostnames:
  - tag:Name
  - public-ip-address
